spring:
  datasource:
    username: root
#    password: zhigang911
    password: root
    #    password: WMMj7w9!N_LyDn#
    url: jdbc:mysql://127.0.0.1:3306/bupt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://39.107.77.0:3306/bupt?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 6000000
      maximum-pool-size: 100
      max-lifetime: 18000000
      minimum-idle: 200
      validation-timeout: 30000
      idle-timeout: 600000

  application:
    name: database
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  data:
    mongodb:
#      uri: mongodb://127.0.0.1:27017/logs
      authentication-database: admin
      username: admin
      password: admin
      database: logs
      host: 127.0.0.1
      port: 27017
  session:
    store-type: mongodb
server:
  port: 8000

logging.level.org.springframework.boot.autoconfigure: ERROR
